package.json, src/components/about/benefit/BenefitDesktop/BenefitDesktop.module.scss, src/components/about/intro/Intro.module.scss, src/components/about/mainBanner/MainBanner.module.scss, src/components/about/mainBanner/MainBanner.tsx, src/components/about/plan/planDesktop/PlanDesktop.module.scss, src/components/about/projectPreiview/projectPreview.module.scss, src/components/layout/navbar/CustomNavbar.tsx, src/components/layout/navbar/customNavbar.module.scss, src/pages/about/style.tsx, yarn.lock
- close #19 
- 아직 반응형 작업 이전이므로 영상 동작만 확인해주시면 될 것 같습니다.
=> #19 about 영상추가

src/components/information/Information.tsx, src/components/layout/navbar/CustomNavbar.tsx
=> [Chore/#25] GNB 수정

src/components/information/information.module.scss, src/components/myPage/myPageBasicInfo/myPageBasicInfo.module.scss, src/components/myPage/myPageDetailedInfo/myPageDetailedInfo.module.scss, src/components/myPage/myPageProject/myPageProject.module.scss, src/components/signUp/signUpCard.module.scss, src/pages/myPage/styles.module.scss, src/pages/updatePW/styles.module.scss
=> [Chore/#27] Breakpoint 설정

src/components/about/findingUniv/FindingUniv.tsx, src/components/recruit/recruitCalendar/RecruitCalendar.module.scss, src/components/recruit/recruitCalendar/RecuritCalendar.tsx, src/components/recruit/recruitCaution/RecruitCaution.module.scss, src/components/recruit/recruitCaution/RecruitCaution.tsx, src/components/recruit/recruitFAQ/RecruitFAQ.module.scss, src/components/recruit/recruitFAQ/RecruitFAQ.tsx, src/components/recruit/recuritHeader/RecuritHeader.tsx, src/components/recruit/recuritTarget/RecuritTarget.tsx, src/pages/errors/NotFound.tsx, src/pages/errors/notFound.module.scss
=> [Refactor/#29] Refactor cx style

src/components/recruit/recruitCalendar/RecruitCalendar.module.scss, src/components/recruit/recruitCaution/RecruitCaution.module.scss, src/components/recruit/recuritHeader/RecruitHeader.module.scss, src/components/recruit/recuritTarget/RecruitTarget.module.scss
=> [Fix/#35] QA 반영

src/assets/svgs/divider.svg, src/components/project/CardProject.tsx, src/components/project/ProjectDetailModal.tsx, src/components/project/projectStyles.module.scss
- close #42 
- 추후 GDS 변경사항이 많아 따로 컴포넌트를 더 나누지 않았습니다. 추후 GDS를 적용해야 할 부분 또한 주석으로 표시해두었습니다.
=> [Feat/#42] 프로젝트 모달 컴포넌트 구현

src/components/about/activity/Activity.module.scss, src/components/about/activity/ActivityItem.tsx, src/components/about/activity/ActivityList.tsx
=> [Fix/#46] About페이지 모바일 환경에서 사진 깨지는 현상 수정

.github/workflows/cicd.yml, Dockerfile, default.conf, vite.config.ts, yarn.lock
=> [Deploy/#50] CICD 파이프라인 구축 및 배포 셋팅

index.html
=> [Hotfix/#57] mixed contents 에러 해결

src/api/instance.ts
=> [Hotfix/#57] BaseURL 변경으로 인한 api 테스트 요청

default.conf, index.html
=> [hotfix/#57] API 프록시 설정

src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/styles.module.scss, src/pages/hackathon/IdeaCreate/TeamPreferenceStep2.tsx
=> [Feat/#66] 필요스택 부분 width수정

src/api/idea.ts, src/components/hackathon/ideaDetail/ideaDetailInfo/TeamInfo.tsx, src/components/hackathon/ideaList/filter/ActiveFilterDropdown.tsx, src/components/hackathon/ideaList/filter/SubjectFilterDropdown.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx
=> [Feat/#71] 아이디어 리스트 api연결 테스트

src/api/idea.ts, src/components/hackathon/ideaDetail/IdeaDetailHeader.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/IdeaInfo.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/styles.module.scss, src/components/hackathon/ideaList/ideaItem/IdeaListItem.tsx, src/pages/hackathon/IdeaDetail/IdeaDetail.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx
- #74 
- 드롭다운 오류의 경우 백엔드부분에서 일부 오류 수정 + nullable 값의 경우 undefined일 경우, 파라미터에 값을 넣지 않게끔 변경
=> [Fix/#74] 아이디어 디테일 및 리스트 수정 테스트

src/components/hackathon/ideaList/ideaItem/IdeaListItem.tsx, src/components/hackathon/ideaList/ideaItem/styles.module.scss, src/pages/hackathon/IdeaDetail/IdeaDetail.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx
=> [Hotfix/#74] 아이디어 디테일 및 리스트 테스트 후 수정

src/components/hackathon/ideaForm/FormDropdown.tsx, src/pages/hackathon/IdeaApply/IdeaApply.tsx
=> [Fix/#83] 아이디어 지원 시 생긴 에러 일부 수정

package.json, src/components/hackathon/ideaDetail/IdeaDetailHeader.tsx, src/components/hackathon/ideaForm/FormEditor.tsx, src/components/hackathon/ideaForm/styles.module.scss, src/components/layout/navbar/CustomNavbar.tsx, src/components/layout/navbar/customNavbar.module.scss, src/hooks/useS3Upload.ts, src/hooks/useUpload.ts, src/pages/hackathon/IdeaDetail/IdeaDetail.tsx, src/store/useAuthStore.ts, yarn.lock
=> [Feat/#78] 마크다운 에디터 수정 및 자잘한 오류 수정

src/api/instance.ts, src/api/system.ts, src/components/hackathon/ideaDetail/IdeaDetailHeader.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/MemberInfoItem.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/TeamInfoCard.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/styles.module.scss, src/components/hackathon/ideaDetail/styles.module.scss, src/components/recruit/recuritHeader/RecuritHeader.tsx, src/pages/hackathon/IdeaApply/styles.module.scss, src/pages/hackathon/IdeaCreate/styles.module.scss, src/pages/hackathon/IdeaDetail/IdeaDetail.tsx, src/pages/hackathon/IdeaDetail/styles.module.scss
- close #92 
- period 불러오는 과정에서 api endpoint가 오타나서 수정하였습니다.
=> [design/#92] 아이디어 부분 breakpoint 추가 및 일부 디자인 수정

src/components/recruit/recruitCalendar/RecuritCalendar.tsx
=> [Chore] 미르미 모집 일자 변경

src/pages/hackathon/IdeaCreate/TeamPreferenceStep2.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/store/useAuthStore.ts
=> [Fix] status를 저장하지 못하는 현상 수정

src/api/users.ts, src/components/hackathon/common/team/MemberInfoItem.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/TeamInfoCard.tsx, src/components/hackathon/ideaForm/FormLinkInput.tsx, src/components/hackathon/ideaForm/PositionForm.tsx, src/components/hackathon/ideaForm/StackSelector.tsx, src/components/hackathon/ideaForm/styles.module.scss, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/pages/hackathon/IdeaCreate/TeamPreferenceStep2.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/myPage/MyPage.tsx, src/pages/myPage/MyPageEdit.tsx, src/store/useAuthStore.ts
- close #94 
- 마이페이지 관련 테스트 필요
=> [feat/#94] 마이페이지 구현

src/api/users.ts, src/components/hackathon/teamBuilding/IdeaApplyListItem.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantPage.tsx, src/store/usePeriodStore.ts
=> [test/#104] 팀 빌딩 내 지원정보 요약

src/Router.tsx, src/api/teams.ts, src/api/users.ts, src/components/hackathon/common/team/MemberInfoItem.tsx, src/components/hackathon/teamBuilding/IdeaApplyListItem.tsx, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantTeamPage.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx
=> [Feat/#104] 팀 정보 조회 및 팀 조회 라우터 변경

src/components/hackathon/ideaForm/FormEditor.tsx, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantTeamPage.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx
=> [Fix/#104] null 가능성 있는 페이지 수정

src/components/hackathon/common/team/MemberInfoItem.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/TeamInfo.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/TeamInfoCard.tsx, src/components/hackathon/teamBuilding/IdeaApplyListItem.tsx, src/components/hackathon/teamBuilding/TeamBuildingPhaseSelector.tsx, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/components/hackathon/teamBuilding/styles.module.scss, src/components/layout/navbar/CustomNavbar.tsx, src/pages/hackathon/IdeaApply/IdeaApply.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/pages/myPage/MyPageEdit.tsx, src/store/useAuthStore.ts
=> [Fix/#109] 테스트 중 발견한 일부 오류 수정

src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx, src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep2.tsx, src/components/hackathon/ideaDetail/IdeaDetailHeader.tsx, src/components/hackathon/ideaForm/FormEditor.tsx, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/components/signUp/SignUpCard.tsx, src/constants/position.ts, src/pages/hackathon/IdeaCreateEdit/TeamPreferenceForm.tsx, src/store/useIdeaFormStore.ts
=> [fix/#115] 테스트 중 발견한 오류 수정 + 등록/수정 오류 수정

src/api/idea.ts, src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx, src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep2.tsx, src/constants/position.ts, src/pages/hackathon/IdeaCreateEdit/TeamPreferenceForm.tsx, src/store/useIdeaFormStore.ts
=> [Fix/#117] 수정모드임에도 detail 불러오지 못하는 현상 수정

src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx, src/components/hackathon/ideaForm/PositionForm.tsx, src/pages/hackathon/IdeaCreateEdit/TeamPreferenceForm.tsx
=> [Feat/#121] 추가로 설정할 예외처리 추가(등록 및 수정)

src/utilities/UnivData.ts
=> [feat/#125] 4기 유니브 데이터 업데이트

src/components/hackathon/ideaList/ideaItem/IdeaListItem.tsx, src/components/hackathon/teamBuilding/TeamBuildingPhaseSelector.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/store/usePeriodStore.ts
=> [style/#127] 각종 스타일 바뀐 부분 수정

src/components/hackathon/ideaForm/PositionForm.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx
=> [Fix/#131] 리팩토링 중 발견된 오류 수정

src/Router.tsx, src/components/admin/sideNav/SideNavigation.tsx, src/components/admin/sideNav/sideNavigation.module.scss, src/components/layout/navbar/CustomNavbar.tsx, src/components/recruit/recruitHeader/RecruitHeader.tsx, src/pages/admin/Admin.tsx, src/pages/admin/admin.module.scss
=> [Chore/#137] 어드민 페이지 라우트 설정 및 사이드바 구현

src/api/admin.ts, src/api/univ.ts, src/components/admin/participantList/univListSideBar/UnivListSidebar.tsx
=> [Fix/#143] api 엔드포인트 수정 후 테스트

src/components/admin/participantList/univListSideBar/UnivListSidebar.tsx
=> [Fix/#143] data 잘못 접근한 부분 수정

src/App.tsx, src/components/admin/participantList/modal/UnivCreateModal.tsx, src/components/admin/participantList/modal/UnivUpdateModal.tsx, src/components/admin/participantList/univListSideBar/UnivListSidebar.tsx
=> [Fix/#143] 유니브 정보 관련 버그 수정

src/pages/admin/period/teamBuildingPeriod/TeamBuildingPeriodPage.tsx
=> [Feat/#151] 기간데이터 변경사항 추가

src/components/admin/participantList/form/MemberForm.tsx, src/components/admin/participantList/form/form.module.scss, src/components/admin/participantList/modal/MemberUpdateModal.tsx
=> [Feat/#149] 유저 정보 수정 시 input 데이터가 바뀌지 않는 현상 수정 

src/api/admin/users.ts, src/components/admin/participantList/modal/MemberUpdateModal.tsx, src/components/admin/participantList/modal/UnivUpdateModal.tsx
=> [Feat/#149] 미르미 및 유니브 관련 API 이슈 해결 테스트 

src/api/admin/univs.ts, src/components/admin/participantList/memberRow/styles.module.scss, src/components/admin/participantList/modal/UnivUpdateModal.tsx, src/pages/admin/participantList/ParticipantList.tsx
=> [Feat/#149] 미르미 목록을 가져와서 대표 지정가능하도록 구현

src/api/admin/teams.ts, src/components/admin/teamList/form/TeamForm.tsx, src/components/admin/teamList/form/TeamInfoView.tsx, src/components/admin/teamList/modal/TeamCreateModal.tsx, src/components/admin/teamList/modal/TeamUpdateModal.tsx, src/components/admin/teamList/teamRow/TeamRow.tsx, src/components/admin/teamList/teamTable/TeamTable.tsx, src/components/admin/teamList/teamTable/teamTable.module.scss, src/components/admin/teamManagement/teamManageTable/teamManageTable.module.scss, src/pages/admin/participantList/ParticipantList.tsx, src/pages/admin/participantList/participantList.module.scss, src/pages/admin/teamListAdmin/TeamList.tsx, src/pages/admin/teamManagement/TeamManagement.tsx, src/types/admin/team.ts
=> [Feat/#157] 팀 데이터 관리 테스트 중 발견한 오류 수정

src/api/admin/system.ts, src/api/admin/teams.ts, src/api/admin/users.ts, src/components/admin/teamList/form/TeamForm.tsx, src/components/admin/teamList/modal/TeamCreateModal.tsx, src/components/admin/teamList/modal/TeamUpdateModal.tsx, src/components/admin/teamList/teamRow/TeamRow.tsx, src/components/admin/teamManagement/modal/TeamMemberCreateModal.tsx, src/components/admin/teamManagement/teamManageRow/TeamManageRow.tsx, src/constants/position.ts, src/pages/admin/period/teamBuildingPeriod/TeamBuildingPeriodPage.tsx, src/pages/admin/teamListAdmin/TeamList.tsx, src/pages/admin/teamManagement/TeamManagement.tsx, src/types/admin/team.ts
=> [Feat/#151] 기간 설정 및 팀 빌딩 일부 이슈 수정 테스트

src/api/admin/teams.ts, src/api/admin/users.ts, src/components/admin/participantList/form/MemberInfoView.tsx, src/components/admin/participantList/memberRow/MemberRow.tsx, src/components/admin/participantList/memberRow/styles.module.scss, src/components/admin/teamList/teamRow/TeamRow.tsx, src/components/admin/teamList/teamRow/teamRow.module.scss, src/components/admin/teamList/teamTable/TeamTable.tsx, src/components/admin/teamManagement/modal/TeamMemberUpdateModal.tsx, src/components/admin/teamManagement/teamManageRow/TeamManageRow.tsx, src/components/admin/teamManagement/teamManageTable/teamManageTable.module.scss
=> [Feat/#157] 팀 정보 관련 이슈 테스트

src/api/admin/users.ts, src/components/admin/participantList/form/MemberForm.tsx, src/components/admin/participantList/form/UnivForm.tsx, src/components/admin/participantList/form/form.module.scss, src/components/admin/participantList/memberRow/MemberRow.tsx, src/components/admin/participantList/memberRow/styles.module.scss, src/components/admin/participantList/memberTable/MemberTable.tsx, src/components/admin/participantList/modal/MemberCreateModal.tsx, src/components/admin/participantList/modal/MemberUpdateModal.tsx, src/components/admin/participantList/modal/UnivCreateModal.tsx, src/components/admin/participantList/modal/UnivUpdateModal.tsx, src/components/admin/participantList/modal/dropdown/UnivSearchDropdown.tsx, src/components/admin/participantList/modal/univUpdateModal.module.scss, src/components/admin/participantList/univListSideBar/UnivListSidebar.tsx, src/components/admin/teamList/form/TeamForm.tsx, src/components/admin/teamList/modal/TeamCreateModal.tsx, src/components/admin/teamList/modal/TeamUpdateModal.tsx, src/components/admin/teamList/teamRow/teamRow.module.scss, src/components/admin/teamManagement/modal/TeamMemberCreateModal.tsx, src/components/admin/teamManagement/modal/TeamMemberUpdateModal.tsx, src/components/admin/teamManagement/teamManageRow/TeamManageRow.tsx, src/pages/admin/participantList/ParticipantList.tsx, src/pages/myPage/MyPageEdit.tsx, src/types/admin/member.ts, src/types/admin/univ.ts, src/types/admin/user.ts
=> [Feat/#149] 어드민 미르미 리스트 발견된 오류 수정 테스트

src/components/admin/participantList/form/UnivForm.tsx, src/components/admin/participantList/memberTable/MemberTable.tsx, src/components/admin/participantList/memberTable/styles.module.scss, src/components/admin/participantList/modal/UnivCreateModal.tsx, src/components/admin/participantList/modal/UnivUpdateModal.tsx, src/components/admin/participantList/univListSideBar/styles.module.scss, src/components/admin/teamList/form/TeamForm.tsx, src/pages/admin/participantList/participantList.module.scss
=> [Feat/#149] 유니브 수정부분 수정 및 UI 개선

src/api/idea.ts, src/api/users.ts, src/components/admin/participantList/modal/UnivUpdateModal.tsx, src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx, src/components/hackathon/common/team/MemberInfoItem.tsx, src/components/hackathon/common/team/styles.module.scss, src/components/hackathon/ideaDetail/ideaDetailInfo/TeamInfo.tsx, src/components/hackathon/ideaDetail/ideaDetailInfo/teamInfo/TeamInfoCard.tsx, src/components/hackathon/teamBuilding/IdeaApplyListItem.tsx, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantPage.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantTeamPage.tsx, src/types/user/team.ts
=> [Fix/#169] 명세 바뀐 부분 수정 테스트

src/api/idea.ts, src/api/teams.ts, src/components/common/searchDropdown/SearchDropdown.tsx, src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx, src/components/hackathon/ideaList/filter/ActiveFilterDropdown.tsx, src/pages/hackathon/IdeaApply/IdeaApply.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantPage.tsx, src/pages/hackathon/teamBuilding/myTeam/MyTeamPage.tsx, src/pages/myPage/styles.module.scss, src/store/usePeriodStore.ts
- #171 
- 💄 **Style**: 스택이 깨지지 않도록 다시 수정  
- ♻️ **Refactor**: 모집 상태 기본값을 "모집 중"으로 변경  
- ♻️ **Refactor**: `status`가 provider인 사용자만 팀명 교체 가능하도록 제한  
- 🐛 **Fix**: 지원 현황 내 지망이 올바르게 보이도록 수정  
- ♻️ **Refactor**: 어떤 모집 기간에도 해당되지 않을 경우 문구 표시 추가  
- 🐛 **Fix**: `SearchDropdown`이 계속 열려있는 문제 수정  
- 🐛 **Fix**: 아이디어 수정 시 주제가 정상적으로 로드되도록 구현
=> [Refactor/#171] QA(~6/8) 2차 테스트

src/components/admin/participantList/memberRow/MemberRow.tsx, src/components/common/searchDropdown/SearchDropdown.tsx, src/components/common/searchDropdown/searchDropdown.module.scss, src/components/hackathon/ideaForm/styles.module.scss, src/pages/updatePW/UpdatePW.tsx
=> [Refactor/#171] QA 3차 테스트

src/pages/admin/participantList/ParticipantList.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx
=> [Refactor/#176] 팀빌딩 기간인지 확인하고 api 요청안되는 현상 해결

src/api/teams.ts, src/components/admin/participantList/memberRow/MemberRow.tsx, src/components/admin/participantList/memberRow/styles.module.scss, src/components/admin/participantList/memberTable/MemberTable.tsx, src/components/admin/participantList/memberTable/styles.module.scss, src/components/admin/participantList/univListSideBar/UnivListSidebar.tsx, src/components/admin/teamList/form/TeamForm.tsx, src/components/admin/teamList/teamRow/TeamRow.tsx, src/components/common/modal/InformationModal.tsx, src/pages/admin/teamListAdmin/TeamList.tsx, src/pages/hackathon/teamBuilding/myTeam/MyTeamPage.tsx, src/pages/hackathon/teamBuilding/myTeam/styles.module.scss, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/pages/hackathon/teamBuilding/provider/styles.module.scss
- #176 
- ♻️ **Refactor**: '나의 팀'에도 팀빌딩 확정 기능 추가  
- ♻️ **Refactor**: 상세 조회 페이지에 `teambuilding` 정보 추가  
- 💄 **Style**: 미르미 리스트 행의 너비 값 지정  
- ♻️ **Refactor**: 유니브 리스트에서 '전체' 클릭 시 항목이 활성화되도록 수정
=> [Feat/#176] 팀빌딩 확정 기능 추가 및 미르미 UI 개선

src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx
=> [!hotfix/#176] 무한 로딩되는 현상 수정

src/components/hackathon/IdeaCreateEdit/TeamPreferenceStep1.tsx, src/components/hackathon/teamBuilding/IdeaApplyListItem.tsx, src/components/hackathon/teamBuilding/TeamInformation.tsx, src/components/hackathon/teamBuilding/skeletonLoading/IdeaApplyListSkeleton.tsx, src/components/hackathon/teamBuilding/skeletonLoading/TeamInformationSkeleton.tsx, src/components/hackathon/teamBuilding/skeletonLoading/ideaApplyListSkeleton.module.scss, src/components/hackathon/teamBuilding/skeletonLoading/teamInformationSkeleton.module.scss, src/pages/hackathon/teamBuilding/applicant/ApplicantPage.tsx, src/pages/hackathon/teamBuilding/applicant/ApplicantTeamPage.tsx, src/pages/hackathon/teamBuilding/myTeam/MyTeamPage.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx
=> [Refactor/#176] 아이디어 수정 시 무한 로딩되는 현상 수정

src/components/admin/ideaManagement/topicModal/TopicModal.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx
=> [Refactor/#186] 필터링 수정 및 api 일부 수정

src/components/admin/ideaManagement/ideaManageTable/ideaManageTable.module.scss, src/components/hackathon/ideaDetail/IdeaDetailHeader.tsx, src/pages/admin/ideaManagement/IdeaManagement.tsx, src/pages/admin/participantList/participantList.module.scss, src/pages/hackathon/IdeaList/styles.module.scss, src/store/useAuthStore.ts
- #191 
- ♻️ **Refactor**: 아이디어 검색 시 `undefined`가 아닌 값으로 인해 API가 계속 호출되는 문제 수정  
- ♻️ **Refactor**: 쿠키 삭제 시 페이지가 새로고침되도록 처리  
- ♻️ **Refactor**: 거절당한 사용자도 재지원 가능하도록 수정  
- 💄 **Style**: 아이디어 관리 페이지의 텍스트 깨짐 현상 수정  
- 💄 **Style**: 리스트 영역 height 조정으로 가독성 개선  
- 💄 **Style**: 리스트 뷰 너비 크기 변경
=> [Refactor/#191] 7/2 QA 2차 테스트

src/api/admin/teams.ts, src/components/admin/sideNav/SideNavigation.tsx, src/components/layout/navbar/CustomNavbar.tsx, src/pages/admin/teamListAdmin/TeamList.tsx, src/store/useAuthStore.ts
=> [Refactor/#191] 7/2 3차 테스트

src/api/admin/idea.ts, src/components/admin/ideaManagement/topicModal/TopicModal.tsx, src/components/hackathon/ideaDetail/IdeaDetailHeader.tsx, src/components/hackathon/ideaForm/FormEditor.tsx, src/components/hackathon/teamBuilding/TeamBuildingPhaseSelector.tsx, src/pages/admin/ideaManagement/IdeaManagement.tsx, src/pages/admin/teamListAdmin/TeamList.tsx, src/pages/admin/teamListAdmin/teamList.module.scss, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/teamBuilding/myTeam/MyTeamPage.tsx, src/pages/hackathon/teamBuilding/myTeam/styles.module.scss, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/pages/hackathon/teamBuilding/provider/styles.module.scss, src/store/useAuthStore.ts, src/store/usePeriodStore.ts, src/types/admin/idea.ts, src/types/user/team.ts
- #195 
- ♻️ **Refactor**: 해커톤 기간이 아닐 경우 등록 버튼 비활성화 및 기간 데이터 추가  
- ♻️ **Refactor**: 팀빌딩이 종료되면 지원하기 버튼 비활성화  
- ♻️ **Refactor**: 해커톤 기간에는 1, 2, 3차 아이디어 전부 보이도록 설정  
- ♻️ **Refactor**: 아이디어 주제 삭제 불가 시 UX 향상을 위한 toast 메시지 추가  
- ♻️ **Refactor**: 팀빌딩 확정 시 뷰 변경 처리  
- ♻️ **Refactor**: 팀 빌딩 확정 후 화면 자동 재로딩 처리  
- 💄 **Style**: 엑셀 내보내기 버튼 추가  
- 🐛 **Fix**: 아이디어 조회 시 정렬(sort)이 작동하지 않는 문제 수정
=> [Refactor/#195] 지금까지 구현된 것들 모두 테스트

src/api/users.ts, src/components/admin/ideaManagement/ideaCountModal/IdeaCountModal.tsx, src/components/admin/participantList/memberTable/MemberTable.tsx, src/components/hackathon/teamBuilding/AcceptableCountIndicator.tsx, src/components/hackathon/teamBuilding/TeamBuildingPhaseSelector.tsx, src/components/hackathon/teamBuilding/styles.module.scss, src/constants/position.ts, src/pages/admin/ideaManagement/IdeaManagement.tsx, src/pages/admin/ideaManagement/ideaManagement.module.scss, src/pages/admin/teamListAdmin/TeamList.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/IdeaList/styles.module.scss, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/pages/myPage/MyPageEdit.tsx, src/store/useAuthStore.ts, src/types/admin/user.ts, src/types/user/idea.ts, src/types/user/users.ts
- #195 
- ♻️ **Refactor**: 지원 현황 차시가 새로고침 후에도 정확하게 반영되도록 수정  
- ♻️ **Refactor**: `PhaseSelector`에 해커톤 기간일 경우의 수 추가  
- ♻️ **Refactor**: 로컬스토리지에 저장된 불필요한 데이터 제거  
- 💄 **Style**: 아이디어 개수 설정 모달 UI 구현  
- 💄 **Style**: 등록 가능한 아이디어 개수 표시 UI 구현  
- ✨ **Feat**: 현재 수락 가능 인원 수 인디케이터 기능 구현
=> [Refactor/#195] 7/6 QA 및 새로운 기능 추가(인원 인디케이터)

src/components/layout/Layout.tsx, src/components/signUp/SignUpCard.tsx
=> [refactor/#195] 전역적으로 값 관리하는 부분 추가

src/components/hackathon/teamBuilding/AcceptableCountIndicator.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/routes/ProtectedRoute.tsx, src/store/useAuthStore.ts
=> [Refactor/#195] 전역 상태 관리 방식 수정

src/components/layout/Layout.tsx, src/components/layout/layout.module.scss
=> [!Hotfix] 레이아웃 수정으로 인해 영상 깨지는 현상 수정 (#195)

src/api/instance.ts, src/components/admin/ideaManagement/ideaCountModal/IdeaCountModal.tsx, src/components/admin/participantList/univListSideBar/styles.module.scss, src/components/admin/teamList/form/TeamInfoView.tsx, src/components/layout/admin/AdminLayout.tsx, src/components/signUp/SignUpCard.tsx, src/pages/hackathon/IdeaApply/IdeaApply.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/store/useAuthStore.ts
- close #207 
- ♻️ **Refactor**: 어드민 페이지에서 새로고침 시 리다이렉트되는 문제 수정  
- ♻️ **Refactor**: 아이디어 정보가 `null`일 경우 버튼 비활성화 처리  
- ♻️ **Refactor**: 아이디어 개수 설정이 정상적으로 로드되도록 개선  
- ♻️ **Refactor**: 아이디어 지원 성공 시 toast 메시지로 UX 개선  
- 💄 **Style**: 유니브 사이드바 `padding` 값 조정
=> [refactor/#207] 어드민 새로고침 이슈 및 아이디어 예외 처리 개선

src/components/hackathon/common/team/MemberInfoItem.tsx
=> [test/#215] imgUrl 디버깅

src/components/about/mainBanner/MainBanner.module.scss, src/components/about/mainBanner/MainBanner.tsx
=> [Refactor/#140] 영상 대체 이미지 추가

src/pages/admin/participantList/ParticipantList.tsx
=> [refactor/#222] 파일 업로드 관련 테스트

src/pages/hackathon/teamBuilding/myTeam/styles.module.scss
=> [Style/#222] 팀 정보 부분 스타일링 변경

src/api/admin/users.ts, src/components/admin/participantList/memberRow/MemberRow.tsx, src/components/admin/participantList/modal/PasswordResetModal.tsx, src/components/admin/participantList/modal/passwordResetModal.module.scss, src/components/layout/footer/CustomFooter.tsx, src/pages/hackathon/IdeaDetail/IdeaDetail.tsx, src/pages/hackathon/IdeaList/IdeaList.tsx, src/pages/hackathon/IdeaList/styles.module.scss
- #233 
- ✨ **Feat**: 어드민 비밀번호 초기화 기능 구현  
- 💄 **Style**: 아이디어 등록 가능 개수 설정 UI 적용  
- ♻️ **Refactor**: 구름톤 유니브 ⓒ 문구(copyright) 변경
=> [Feat/Style/#233] 어드민 비밀번호 초기화 기능 및 UI 개선 

src/components/admin/participantList/modal/passwordResetModal.module.scss, src/components/layout/navbar/CustomNavbar.tsx, src/components/layout/navbar/customNavbar.module.scss, src/components/myPage/MyPageHeader.tsx, src/pages/hackathon/teamBuilding/provider/ProviderPage.tsx, src/pages/hackathon/teamBuilding/provider/styles.module.scss
- #236 
- 🚑 **Hotfix**: 마이페이지에서 사용자 이름이 보이지 않는 문제 수정  
- ♻️ **Refactor**: 어드민 페이지 내 비밀번호 초기화 내용을 중앙 정렬로 수정  
- ♻️ **Refactor**: provider 관점에서 팀 정보 삭제 처리  
- ♻️ **Refactor**: 로그인 버튼에 있던 alert 제거 및 팀빌딩 기간 추가
=> [Refactor/#236] 마이페이지 이름 표시 버그 및 팀빌딩 UI 개선

src/components/admin/participantList/univListSideBar/styles.module.scss
=> Style: 어드민 명단부분 height값 수정 (#236)

src/api/admin/teams.ts, src/pages/admin/teamListAdmin/TeamList.tsx
=> Feat: 팀 정보 엑셀로 내보내기 기능 구현 (#236)

src/api/admin/teams.ts, src/components/admin/participantList/univListSideBar/styles.module.scss
=> !hotfix: 엔드포인트 수정 (#241)

src/api/admin/teams.ts, src/pages/admin/teamListAdmin/TeamList.tsx
=> [Hotfix/#245] 엑셀 데이터 추출 및 페이지네이션 오류 수정

src/components/myPage/QRCheckInModal.tsx
=> [Chore/#248] console 추가해서 확인

src/hooks/useQRUserInfo.ts
=> [Fix/#248] api 데이터를 읽지못하는 현상 수정
